# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/terminal_assist',
                'doc_host': 'https://ncoop57.github.io',
                'git_url': 'https://github.com/ncoop57/terminal_assist',
                'lib_path': 'terminal_assist'},
  'syms': {'terminal_assist.core': {'terminal_assist.core.foo': ('core.html#foo', 'terminal_assist/core.py')}}}