# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/terminal_assist',
                'doc_host': 'https://ncoop57.github.io',
                'git_url': 'https://github.com/ncoop57/terminal_assist',
                'lib_path': 'terminal_assist'},
  'syms': { 'terminal_assist.cli': {'terminal_assist.cli.term_assist': ('cli.html#term_assist', 'terminal_assist/cli.py')},
            'terminal_assist.core': { 'terminal_assist.core.TerminalAssistant': ('core.html#terminalassistant', 'terminal_assist/core.py'),
                                      'terminal_assist.core.TerminalAssistant.action_toggle_dark': ( 'core.html#terminalassistant.action_toggle_dark',
                                                                                                     'terminal_assist/core.py'),
                                      'terminal_assist.core.TerminalAssistant.compose': ( 'core.html#terminalassistant.compose',
                                                                                          'terminal_assist/core.py'),
                                      'terminal_assist.core.TerminalAssistant.on_input_submitted': ( 'core.html#terminalassistant.on_input_submitted',
                                                                                                     'terminal_assist/core.py'),
                                      'terminal_assist.core.TerminalAssistant.on_ready': ( 'core.html#terminalassistant.on_ready',
                                                                                           'terminal_assist/core.py')}}}