# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% auto 0
__all__ = ['term_assist']

# %% ../nbs/01_cli.ipynb 2
import os

from fastcore.script import call_parse, Param
from .core import TerminalAssistant

# %% ../nbs/01_cli.ipynb 4
@call_parse
def term_assist():
    "Term assist"
    print("Term assist")
    # check that the OpenAI API key is set
    if not os.environ.get("OPENAI_API_KEY"):
        raise Exception("Please set your OpenAI API key as an environment variable. You can set it in your .bashrc file with the following line: export OPENAI_API_KEY=YOUR_API_KEY")
    app = TerminalAssistant()
    app.run()
